<?php

namespace AppBundle\Repository;

/**
 * FortuneCookieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FortuneCookieRepository extends \Doctrine\ORM\EntityRepository
{
}
