<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;

/**
 * FortuneCookieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FortuneCookieRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNumberPrintedForCategory(Category $category)
    {
        return $this->createQueryBuilder('fc')
            ->andWhere('fc.category = :category')
            ->setParameter('category', $category)
//            Select() pour annuler le 1er select 'fc' !!
        ->select('SUM(fc.numberPrinted) as fortunesPrinted')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
